# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  ALLURE_VERSION: "2.10.0"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Tests on JDK
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15 ]  # doesn't work on 16

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Build with Maven
        id: build
        continue-on-error: false
        run: mvn compile

      - name: Start Selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        if: github.event_name == 'pull_request'
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome:92.0
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status
        if: github.event_name == 'pull_request'

      - name: Tests
        id: ftests
        timeout-minutes: 10
        run: mvn test -Pci

      - name: Get Allure history
        uses: actions/checkout@v2
        id: allure-setup
        if: steps.build.outcome == 'success'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: allure-history

      - name: Upload Allure report
        uses: actions/upload-artifact@master
        if: github.event_name == 'pull_request' && failure()
        with:
          name: Allure report
          path: target/allure-report

      - name: Deploy Allure report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history